### ISSUE TITLE
VPC module throwing errors

### ISSUE THREAD

**Issue by tgallagher91** [thinkstack-co/terraform-modules#29]
s3 endpoint on line 193 is causing issues, it is commented out in tag 0.15.2, but we will likely need to fix this until we upgrade cjm, sol, and cct to tf12

**Comment by tgallagher91** [comment]
this issue is occurring across all version of terraform, not just version 11.

**Comment by jakeasarus** [comment]
Change did not fix the issue, just removed some necessary code from the module. We are looking into how to fix long term.

**Comment by jakeasarus** [comment]
### Data Provides Multiple Results
We currently receive this error when trying to run terraform plans:
![image](https://user-images.githubusercontent.com/47454060/106972265-869c4480-671e-11eb-82cc-04c1c8ecf9d8.png)

The reason for this is because there are multiple matches for VPC endpoint services that contain S3. Code below.
https://github.com/thinkstack-co/terraform-modules/blob/b3098f0fb10146d86596a17ae224439c4bf0fa8d/modules/aws/vpc/main.tf#L197-L199

To fix this issue what is needed is to narrow down the search to 1 VPC endpoint service. However, the issue with this is that there are 2 VPC endpoints for S3 that have the same endpoint name. 

To see there are two services with the same name
Command:
`aws ec2 describe-vpc-endpoint-services --filters Name=service-name,Values=com.amazonaws.us-east-1.s3`
Results:
![image](https://user-images.githubusercontent.com/47454060/106973280-8f8e1580-6720-11eb-98a6-736469e622dd.png)

### Problems

There is now way to differentiate between these two services. If we look at trying to filter the AWS documentation shows us that we have no filter that would differentiate the two. [Source](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-vpc-endpoint-services.html).

Example from source:
![image](https://user-images.githubusercontent.com/47454060/106973594-26f36880-6721-11eb-8a1f-a7d2c331003f.png)

It would seem to be impossible to narrow it down to just one result. That would be a problem if the data were doing anything, but when we run a command with the same filters present in the code in the AWS cli we return no results. 


Command:
`aws ec2 describe-vpc-endpoints --filters Name=service-name,Values=s3`
Results:
![image](https://user-images.githubusercontent.com/47454060/106972642-44bfce00-671f-11eb-805a-254f70345c21.png)

Since the CLI command shows no results, it makes me think that there are actually no results for this data block and it is effectively just providing an empty string. The data is pushed through to this block:
https://github.com/thinkstack-co/terraform-modules/blob/b3098f0fb10146d86596a17ae224439c4bf0fa8d/modules/aws/vpc/main.tf#L201-L205

### Solution

At this point we know that the error was a result of the data filter not narrowing down the services to just one result, but we also know that the data cannot narrow the result down enough to be useful, therefore I would suggest we remove these lines from the module. 

https://github.com/thinkstack-co/terraform-modules/blob/b3098f0fb10146d86596a17ae224439c4bf0fa8d/modules/aws/vpc/main.tf#L197-L199


We still need to fix the endpoint that is referencing that data though. To do that I would propose that we change line 204 from this location

https://github.com/thinkstack-co/terraform-modules/blob/b3098f0fb10146d86596a17ae224439c4bf0fa8d/modules/aws/vpc/main.tf#L201-L205

Which would be changed to this:
`service_name = element("com.amazonaws.${var.vpc_region}.s3", count.index)`

Then add a variable to the variables file. 
`variable "vpc_region" {
  description = "The region for the VPC"
}`

Last, update the requirements for the module to require vpc_region to be used in the VPC's. This would allow us to have a region specified so that the S3 endpoint would be valid no matter the region.

### Confirmation
Confirmed successful cases:

- ventura_prod_infrastructure

From main.tf:
![image](https://user-images.githubusercontent.com/47454060/106974361-96b62300-6722-11eb-9e97-f3293ab17fce.png)

Last Run:
![image](https://user-images.githubusercontent.com/47454060/106974578-ec8acb00-6722-11eb-8700-d31feb8f6f75.png)

To confirm the run had this new code you can view commit 0c9066d [here](https://github.com/thinkstack-co/ventura_prod_infrastructure/commits/master). You will see source set to the branch.

- [ ] Code for TF 12 has this fix. Review and discuss with @zachreborn, see branch [dev_actually_fix_s3_endpoints](https://github.com/thinkstack-co/terraform-modules/tree/dev_actually_fix_s3_endpoint)
- [ ] Figure out how to implement the same fix in TF 11, syntax is difficult. Work in progress on branch [dev_vpc_fix_tf_11](https://github.com/thinkstack-co/terraform-modules/tree/dev_vpc_fix_tf_11)
- [ ] Discuss endpoints with @zachreborn and determine if they are doing anything yet. From what I can tell no clients have VPC endpoints.

**Comment by jakeasarus** [comment]
Per zach edit this block and remove count, it should not be necessary. 

https://github.com/thinkstack-co/terraform-modules/blob/8422c8c47c3820043322d1ee0bc72f3e9d54e8f5/modules/aws/vpc/main.tf#L207-L214
